import type { Metadata } from "next"

import { Container, Header } from "@/components"
import { inter, jetBrains } from "@/lib"
import { Providers } from "@/providers"
import "@/styles/main.css"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${inter.className} ${jetBrains.variable} dark antialiased`}>
				<Providers>
					<Header />
					<main className="mt-12">
						<Container>{children}</Container>
					</main>
				</Providers>
			</body>
		</html>
	)
}
